apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codercestfun-pvc
spec:
  accessModes:
    # - ReadWriteOnce
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi